# Generated by Django 5.0.1 on 2024-03-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_chat_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lose_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='win_count',
        ),
    ]
